### ISSUE TITLE
type definitions for xast

### ISSUE THREAD

**Issue by stefanprobst** [syntax-tree/xast#1]
### Subject of the feature

add `@types/xast` package to DefinitelyTyped.

i have type definitions for `xast` (modeled after the ones for `hast`), and a PR ready for DefinitelyTyped (see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...stefanprobst:master)) but wanted to first ask if you have any guidelines to follow wrt to typings, and if i should add somebody as maintainer for the `@types/xast` package?

**Comment by ChristianMurphy** [comment]
Welcome @stefanprobst, thanks for contributing typings for xast!

> first ask if you have any guidelines to follow wrt to typings

Generally unified/syntax-tree typings target typescript 3.0+ (which you've already done :+1: ), avoid `any` types (also already done :tada: ), and where possible specify the possible children (also in your branch :rocket: )

> if i should add somebody as maintainer

This is up to you. :man_shrugging: 
@rokt33r, @wooorm, and I (@ChristianMurphy) help maintain several of the other syntax-tree typings: `unist`, `mdast`, and `hast`. 
You're welcome to include more people if you want.

**Comment by stefanprobst** [comment]
cool thanks! => https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48265

**Comment by stefanprobst** [comment]
Thanks for reviewing! released as [`@types/xast@1.0.0`](https://www.npmjs.com/package/@types/xast).
