### ISSUE TITLE
Add warning about `npm install xast`

### ISSUE THREAD

**Issue by siefkenj** [syntax-tree/xast#3]
It appears that `npm install xast` now installs https://github.com/3axap4eHko/xast which is a project unrelated to unifiedjs's xast project. This other `xast` comes with conflicting types. The author appears unwilling to change the name of their project.

I suggest adding a warning in the documentation that `npm install xast` will **not** install this package and will instead install a conflicting package. (I had to spend some time today debugging only to realize the problem was the conflict between the `@types/xast` and `xast` packages.)

**Comment by wooorm** [comment]
Thanks, added what to install!
